routes/web.php
<?php

use Spatie\Permission\Models\Permission;
use Carbon\Carbon;

define('ADMIN_PATH', 'admin');
define('FRONT_PATH', 'front');

Route::get('/test', function () {
$now =time();
$oneYearFfromNow = date('Y-M-d',$now);
dd( $oneYearFfromNow);
});

Route::get('/add_perm', function () {
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return view('home');
});

Auth::routes();


Route::group(['prefix' => ADMIN_PATH], function () {

    # admin authentication area
    Route::group(['namespace' => 'Auth\Admin'], function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login')->name('admin.login');
        Route::get('logout', 'LoginController@logout')->name('admin-logout');

        # admin reset password routes
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('password/reset/{token}', 'ResetPasswordController@showLinkRequestForm')->name('admin.password.reset');
    }); # end of admin auth area

    # admin namespace area
    Route::group(['namespace' => 'Admin', 'middleware' => 'auth:admin'], function () {

        Route::get('/', 'DashboardController@index')->name('admin.dashboard');

        Route::resource('/admin', 'AdminController');
        Route::resource('/employees', 'EmployeeController');
        Route::resource('/departments', 'DepartmentController');
        Route::resource('/designations', 'DesignationController');
        Route::resource('/clients', 'ClientController');
        Route::resource('/holidays' , 'HolidayController');
        Route::resource('/company_profiles' , 'CompanyProfileController');

    }); # end of admin namespace
}); # end of admin area

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = ['name', 'image', 'email','phone','client_id','company_name','job_title'];
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Client ;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB ;


class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $clients = Client::all();
         $search = $request->get('search');
        $c = DB::table('clients')->where('name' , 'like' , '%'.$search.'%');
        return view('admin.clients.index',compact('clients' , 'search' , 'c'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::all();
        return view('admin.clients.create',compact('clients'));
    }
    public function search(Request $request){

        // return Redirect('admin/clients');
        return view('admin.clients.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'           =>'required',
            'image'          => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'email'          =>'required',
            'phone'          =>'required',
            'client_id'      => 'required',
            'company_name'   =>'required',
            'job_title'      => 'required'
        ]);

            $imageName = time().'.'.request()->image->getClientOriginalExtension();
            request()->image->move(public_path('images'), $imageName);
            $clients = new Client([
                'name'            => $request->name,
                'image'           =>  $imageName,
                'email'           => $request->email,
                'phone'           => $request->phone,
                'client_id'       => $request->client_id,
                'company_name'    => $request->company_name,
                'job_title'       =>  $request->job_title
            ]);
            $clients->save();
            // return 'fdf';
            return Redirect('admin/clients');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clients =Client::find($id);
        return view('admin.clients.edit',compact('clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $imageName = time().'.'.request()->image->getClientOriginalExtension();
        request()->image->move(public_path('images'), $imageName);
        $clients = Client::find($id);
        $clients->update([
            $clients->name = $request->name,
            $clients->image = $imageName,
            $clients->email = $request->email,
            $clients->phone = $request->phone,
            $clients->client_id = $request->client_id,
            $clients->company_name = $request->company_name,
            $clients->job_title = $request->job_title

        ]);
        $clients->save();
        return Redirect('admin/clients');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $clients = Client::find($id);
        $clients->delete();
        return Redirect('admin/clients');
    }
}

resources/views/admin/clients/create.blade.php
@extends('admin.layouts.index')

@section('content')

<div class="row">
    <div class="col-md-12">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div>
            @endif

            @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
            @endif
        <form method="POST" action="{{route('clients.store')}}" enctype="multipart/form-data">
            {{csrf_field()}}
            <h3 class="page-title"> إضافة عميل جديد </h3>
            <hr>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label> الأسم </label>
                        <input class="form-control" type="text" name="name">
                    </div>
                </div>
                <div class="col-sm-3">
                        <label>الصورة </label>
                        <input type="file" class="form-control" name="image">
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>Client ID</label>
                        <input class="form-control" name="client_id" type="text">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>الأيميل</label>
                        <input class="form-control" type="email" name="email">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>رقم التليفون</label>
                        <input class="form-control" type="text" name="phone">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>الوظيفة</label>
                        <input class="form-control" name="job_title" type="text">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>أسم الشركة </label>
                        <input class="form-control" type="text" name="company_name">
                    </div>
                </div>
            </div>
            <div class="submit-section">
                <button class="btn btn-primary submit-btn">حفظ</button>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/clients/edit.blade.php
@extends('admin.layouts.index')

@section('content')

<div class="row">
    <div class="col-md-12">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div>
            @endif

            @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
            @endif
            <form method="POST" action="{{route('clients.update' , $clients->id)}}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="put">
            <h3 class="page-title"> تعديل بيانات عميل  </h3>
            <hr>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label> Name </label>
                    <input class="form-control" type="text" name="name" value="{{$clients->name}}">
                    </div>
                </div>
                <div class="col-sm-3">
                        <label>image </label>
                        <input type="file" class="form-control" name="image" >
                        <img src = " {{asset('images/' . $clients->image)}}">
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>Client ID</label>
                        <input class="form-control" name="client_id" type="text" value="{{$clients->client_id}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Email</label>
                        <input class="form-control" type="email" name="email" value="{{$clients->email}}">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Phone Number</label>
                        <input class="form-control" type="text" name="phone" value="{{$clients->phone}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Job Tilte</label>
                        <input class="form-control" name="job_title" type="text" value="{{$clients->job_title}}">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Company Name</label>
                        <input class="form-control" type="text" name="company_name" value="{{$clients->company_name}}">
                    </div>
                </div>
            </div>
            <div class="submit-section">
                <button class="btn btn-primary submit-btn">Save Change</button>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/clients/index.blade.php
@extends('admin.layouts.index')
@section('content')

<!-- Page Content -->
<div class="content container-fluid">
        <!-- Page Title -->
        <div class="row">
            <div class="col">
                <h4 class="page-title">العملاء</h4>
            </div>
            <div class="col-12 text-right m-b-30">
             <a href="{{route('clients.create')}}" class="btn add-btn"><i class="fa fa-plus"></i> إضافة عميل</a>
            </div>
        </div>
        <!-- Page Title -->
        <!-- Search Filter -->
        <form action="{{route('clients.index')}}" method="GET">
                {{csrf_field()}}
            <div class="row filter-row">
                <div class="col-sm-6 col-md-6">
                    <div class="form-group form-focus">
                        <input type="search" class="form-control floating" name="search">
                        <label class="focus-label">الأسم </label>
                    </div>
                </div>
                <div class="col-sm-6 col-md-2">
                    <button type="submit" class="btn btn-success btn-block" style="font-size: 110%"> بحث </button>
                </div>
            </div>
        </form>
        <!-- Search Filter -->

        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped custom-table datatable">
                        <thead>
                            <tr>
                                <th>ألاسم</th>
                                <th>Client ID</th>
                                <th>أسم الشركة </th>
                                <th>الأيميل</th>
                                <th>رقم التليفون</th>
                                <th>الوظيفة</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <div class="form-group row">
                            {{-- <div class="col-10">
                                <input class="form-control" type="date">
                            </div> --}}
                        <tbody>
                            @foreach ($clients as $client)
                            <tr>
                                <td>
                                    <h2 class="table-avatar">
                                        <a class="avatar"><img src="{{ asset('images/'.$client->image) }}" alt=""></a>
                                        <a>{{ $client->name }}</a>
                                    </h2>
                                </td>
                                <td>{{$client->client_id}}</td>
                                <td> {{$client->company_name}}</td>
                                <td>{{ $client->email}}</td>
                                <td>{{ $client->phone}}</td>
                                <td>{{ $client->job_title}}</td>
                                <td class="text-right">
                                    <form method="post" action="{{route('clients.destroy', $client->id)}}">
                                        <span>
                                            <a href="{{ route('clients.edit', $client->id) }}"><i class="btn btn-primary"  >تعديل </i></a>
                                        </span>
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE" />
                                            <div class="btn-group">
                                                <button  onclick="return confirm(' هل انت متاكد ؟؟')" class="btn btn-danger" type="submit">حذف</button>
                                            </div>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /Page Content -->


@endsection