routes/web.php
<?php

use Spatie\Permission\Models\Permission;
use Carbon\Carbon;

define('ADMIN_PATH', 'admin');
define('FRONT_PATH', 'front');

Route::get('/test', function () {
$now =time();
$oneYearFfromNow = date('Y-M-d',$now);
dd( $oneYearFfromNow);
});

Route::get('/add_perm', function () {
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return view('home');
});

Auth::routes();


Route::group(['prefix' => ADMIN_PATH], function () {

    # admin authentication area
    Route::group(['namespace' => 'Auth\Admin'], function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login')->name('admin.login');
        Route::get('logout', 'LoginController@logout')->name('admin-logout');

        # admin reset password routes
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('password/reset/{token}', 'ResetPasswordController@showLinkRequestForm')->name('admin.password.reset');
    }); # end of admin auth area

    # admin namespace area
    Route::group(['namespace' => 'Admin', 'middleware' => 'auth:admin'], function () {

        Route::get('/', 'DashboardController@index')->name('admin.dashboard');

        Route::resource('/admin', 'AdminController');
        Route::resource('/employees', 'EmployeeController');
        Route::resource('/departments', 'DepartmentController');
        Route::resource('/designations', 'DesignationController');
        Route::resource('/clients', 'ClientController');
        Route::resource('/holidays' , 'HolidayController');
        Route::resource('/company_profiles' , 'CompanyProfileController');

    }); # end of admin namespace
}); # end of admin area

app/Models/Designation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Department;
class Designation extends Model
{
    protected $fillable = ['name' , 'department_id'];
    public function Department(){
        return $this->belongsTo('App\Department' , 'department_id');
    }
}

app/Http/Controllers/Admin/DesignationController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Department;
use App\Models\Designation;

class DesignationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = Department::all();
        $designations = Designation::all();
        return view('admin.designations.index',compact('departments' , 'designations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        $designations = Designation::all();
        return view('admin.designations.create',compact('departments' , 'designations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  =>'required',
            'department_id' =>'required'
        ]);
            $designations = new Designation([
                'name'       => $request->name,
                'department_id' =>$request->department_id,
            ]);
            // dd($designations);
            $designations->save();
            return Redirect('admin/designations');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $departments =Department::find($id);
        $designations = Designation::find($id);
        return view('admin.designations.edit',compact('departments' , 'designations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $designations = Designation::find($id);
        $designations->update([
            $designations->name = $request->name,
            $designations->department_id = $request->department_id,
        ]);

        $designations->save();
        return Redirect('admin/designations');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $designation = Designation::find($id);
        $designation->delete();
        return Redirect('admin/designations');
    }
}

resources/views/admin/designations/create.blade.php
@extends('admin.layouts.index')

@section('content')

<div class="row">
    <div class="col-md-12">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div>
            @endif

            @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
            @endif
        <form  method="POST" action="{{route('designations.store')}}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <h3 class="page-title">إضافة وظيفة جديدة  </h3>
            <hr>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label style="font-size: 120%">المُسمى الوظيفى </label>
                        <input class="form-control" type="text" name="name" >
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label style="font-size: 120%">القسم</label>
                        <select class="form-control select" name="department_id">
                        @foreach ($departments as $department)
                        <option value="{{ $department->id }}">{{$department->name}}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div class="submit-section">
                <button class="btn btn-primary submit-btn">حفظ</button>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/designations/edit.blade.php
@extends('admin.layouts.index')

@section('content')

<div class="row">
    <div class="col-md-12">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div>
            @endif

            @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
            @endif
            <form method="POST" action="{{route('designations.update' , $designations->id)}}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="put">
            <h3 class="page-title">تعديل الوظيفة </h3>
            <hr>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label style="font-size: 120%">المُسمى الوظيفى </label>
                    <input class="form-control" type="text" name="name" value="{{$designations->name}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label style="font-size: 120%">القسم</label>
                        <select class="form-control select" name="department_id">
                            @foreach ($designations as $designation)
                                <option>{{ $designation->department->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div class="submit-section">
                <button class="btn btn-primary submit-btn">Save</button>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/designations/index.blade.php
@extends('admin.layouts.index')

@section('content')
<!-- Page Content -->
<div class="content container-fluid">

    <!-- Page Title -->
    <div class="row">
        <div class="col-sm-5 col-5">
            <h4 class="page-title">الوظائف</h4>
        </div>
        <div class="col-sm-7 col-7 text-right m-b-30">
            <a href="{{route('designations.create')}}" class="btn add-btn"><i class="fa fa-plus"></i> إضافة وظيفة</a>
        </div>
    </div>
    <!-- /Page Title -->

    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped custom-table mb-0 datatable">
                    <thead>
                        <tr>
                            <th style="width: 30px;">#</th>
                            <th style="font-size: 120%">الوظيفة </th>
                            <th style="font-size: 120%">القسم </th>
                            <th class="text-right">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($designations as $designation)
                            <tr>
                                <td>{{$designation->id}}</td>
                                <td>{{$designation->name}}</td>
                                {{-- <td>{{ App\Department::find($designation->department_id)->name}}</td> --}}
                                <td>{{$designation->department->name}}</td>
                                <td class="text-right">
                                    <form method="post" action="{{route('designations.destroy', $designation->id)}}">
                                       {{csrf_field()}}
                                       <span>
                                            <a href="{{ route('designations.edit', $designation->id) }}">
                                                <i class="btn btn-primary" >تعديل </i>
                                            </a>
                                        </span>
                                                <input type="hidden" name="_method" value="DELETE" />
                                                <div class="btn-group">
                                                    <button  onclick="return confirm(' هل انت متاكد ؟؟')" class="btn btn-danger" type="submit">حذف</button>
                                                </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /Page Content -->





@endsection