routes/web.php
<?php

use Spatie\Permission\Models\Permission;
use Carbon\Carbon;

define('ADMIN_PATH', 'admin');
define('FRONT_PATH', 'front');

Route::get('/test', function () {
$now =time();
$oneYearFfromNow = date('Y-M-d',$now);
dd( $oneYearFfromNow);
});

Route::get('/add_perm', function () {
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return view('home');
});

Auth::routes();


Route::group(['prefix' => ADMIN_PATH], function () {

    # admin authentication area
    Route::group(['namespace' => 'Auth\Admin'], function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login')->name('admin.login');
        Route::get('logout', 'LoginController@logout')->name('admin-logout');

        # admin reset password routes
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('password/reset/{token}', 'ResetPasswordController@showLinkRequestForm')->name('admin.password.reset');
    }); # end of admin auth area

    # admin namespace area
    Route::group(['namespace' => 'Admin', 'middleware' => 'auth:admin'], function () {

        Route::get('/', 'DashboardController@index')->name('admin.dashboard');

        Route::resource('/admin', 'AdminController');
        Route::resource('/employees', 'EmployeeController');
        Route::resource('/departments', 'DepartmentController');
        Route::resource('/designations', 'DesignationController');
        Route::resource('/clients', 'ClientController');
        Route::resource('/holidays' , 'HolidayController');
        Route::resource('/company_profiles' , 'CompanyProfileController');

    }); # end of admin namespace
}); # end of admin area

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Models\Designation;
class Department extends Model
{
    protected $fillable = ['name'];
    public function Designation(){
        
        return $this->hasMany('App\Models\Designation', 'department_id');
    }
}

app/Http/Controllers/Admin/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Department;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $department = Department::all();
        $departments = Department::all();
        return view('admin.departments.index', compact('departments')) ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.departments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  =>'required',
        ]);
            $departments = new Department([
                'name'       => $request->name,
            ]);
            $departments->save();
            return Redirect('admin/departments');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $departments =Department::find($id);
        return view('admin.departments.edit',compact('departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $departments = Department::find($id);
        $departments->update([
            $departments->name = $request->name,
        ]);
        $departments->save();
        return Redirect('admin/departments');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $departments = Department::find($id);
        $departments->delete();
        return Redirect('admin/departments');
    }
}

resources/views/admin/departments/create.blade.php
@extends('admin.layouts.index')

@section('content')

<div class="row">
    <div class="col-md-12">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div>
            @endif

            @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
            @endif
        <form method="POST" action="{{route('departments.store')}}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <h3 class="page-title"> إضافة قسم جديد </h3>
            <hr>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label style="font-size: 150%">أسم القسم <span class="text-danger"></span></label>
                        <input class="form-control" type="text" name = "name">
                    </div>
                </div>
            </div>

            <div class="submit-section">
                <button class="btn btn-primary submit-btn">أضف</button>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/departments/edit.blade.php
@extends('admin.layouts.index')

@section('content')

<div class="row">
    <div class="col-md-12">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div>
            @endif

            @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
            @endif
        <form method="POST" action="{{route('departments.update' , $departments->id)}}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="put">
            <h3 class="page-title">تعديل القسم </h3>
            <hr>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label style="font-size: 150%">أسم القسم <span class="text-danger"></span></label>
                    <input class="form-control" type="text" name = "name" value="{{$departments->name}}">
                    </div>
                </div>
            </div>

            <div class="submit-section">
                <button class="btn btn-primary submit-btn">حفظ</button>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/departments/index.blade.php
@extends('admin.layouts.index')
@section('content')

    <!-- Page Content -->
    <div class="content container-fluid">
        <!-- Page Title -->
        <div class="row">
            <div class="col-sm-5 col-5">
                <h4 class="page-title">الأقسام</h4>
            </div>
            <div class="col-sm-7 col-7 text-right m-b-30">
                <a href="{{ route('departments.create') }}" class="btn add-btn" ><i class="fa fa-plus"></i>إضافة قسم </a>
            </div>
        </div>
        <!-- /Page Title -->
        <div class="row">
            <div class="col-md-12">
                <div>
                    <table class="table table-striped custom-table mb-0 datatable">
                        <thead>
                            <tr>
                                <th style="width: 40px;">#</th>
                                <th style="width: 80% ; font-size: 120%">أسم القسم</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($departments as $department)
                            <tr>
                                <td>{{$department->id}}</td>
                                <td> {{$department->name}}</td>
                                <td>
                                    <form method="post" action="{{route('departments.destroy', $department->id)}}">
                                        <span>
                                            <a href="{{ route('departments.edit', $department->id) }}"><i class="btn btn-primary"  >تعديل </i></a>
                                        </span>
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE" />
                                            <div class="btn-group">
                                                <button  onclick="return confirm(' هل انت متاكد ؟؟')" class="btn btn-danger" type="submit">حذف</button>
                                            </div>
                                    </form>
                                        </span>
                                    </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /Page Content -->

@endsection