routes/web.php
<?php

use Spatie\Permission\Models\Permission;
use Carbon\Carbon;

define('ADMIN_PATH', 'admin');
define('FRONT_PATH', 'front');

Route::get('/test', function () {
$now =time();
$oneYearFfromNow = date('Y-M-d',$now);
dd( $oneYearFfromNow);
});

Route::get('/add_perm', function () {
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return view('home');
});

Auth::routes();


Route::group(['prefix' => ADMIN_PATH], function () {

    # admin authentication area
    Route::group(['namespace' => 'Auth\Admin'], function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login')->name('admin.login');
        Route::get('logout', 'LoginController@logout')->name('admin-logout');

        # admin reset password routes
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('password/reset/{token}', 'ResetPasswordController@showLinkRequestForm')->name('admin.password.reset');
    }); # end of admin auth area

    # admin namespace area
    Route::group(['namespace' => 'Admin', 'middleware' => 'auth:admin'], function () {

        Route::get('/', 'DashboardController@index')->name('admin.dashboard');

        Route::resource('/admin', 'AdminController');
        Route::resource('/employees', 'EmployeeController');
        Route::resource('/departments', 'DepartmentController');
        Route::resource('/designations', 'DesignationController');
        Route::resource('/clients', 'ClientController');
        Route::resource('/holidays' , 'HolidayController');
        Route::resource('/company_profiles' , 'CompanyProfileController');

    }); # end of admin namespace
}); # end of admin area

resources/views/admin/layouts/errors.blade.php
@push('scripts')
	{!! Html::script('assets/admin/demo/default/custom/components/base/toastr.js') !!}
	<script type="text/javascript">
		toastr.options = {
			  "closeButton": false,
			  "debug": false,
			  "newestOnTop": false,
			  "progressBar": false,
			  "positionClass": "toast-top-right",
			  "preventDuplicates": true,
			  "onclick": null,
			  "showDuration": "300",
			  "hideDuration": "1000",
			  "timeOut": "10000",
			  "extendedTimeOut": "1000",
			  "showEasing": "swing",
			  "hideEasing": "linear",
			  "showMethod": "fadeIn",
			  "hideMethod": "fadeOut"
		};

		@if (session()->has('success'))
			toastr.success("{{ session()->get('success') }}", "Success");
		@elseif (session()->has('failed'))
			toastr.error("{{ session()->get('failed') }}", "Error");
		@elseif (session()->has('notice'))
			toastr.warning("{{ session()->get('notice') }}", "Success");
		@elseif (session()->has('status'))
			toastr.info("{{ session()->get('status') }}", "Success");
		@endif

	</script>

@endpush

resources/views/admin/layouts/index.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <meta name="description" content="Smarthr - Bootstrap Admin Template">
		<meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern, accounts, invoice, html5, responsive, CRM, Projects">
        <meta name="author" content="Dreamguys - Bootstrap Admin Template">
        <meta name="robots" content="noindex, nofollow">
        <title>ASCE-HR</title>

		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png">

		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{{ asset('assets/admin/plugins/bootstrap-rtl/css/bootstrap.min.css') }}">

		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{{ asset('assets/admin/css/font-awesome.min.css') }}">

		<!-- Lineawesome CSS -->
        <link rel="stylesheet" href="{{ asset('assets/admin/css/line-awesome.min.css') }}">

		<!-- Main CSS -->
        <link rel="stylesheet" href="{{ asset('assets/admin/css/style.css') }}">

        <script src="{{ asset('assets/admin/js/html5shiv.min.js') }}"></script>
        <script src="{{ asset('assets/admin/js/respond.min.js') }}"></script>

    </head>
    <body>
		<!-- Main Wrapper -->
        <div class="main-wrapper">

            @include('admin.layouts.header')

            @include('admin.layouts.menu')

			<!-- Page Wrapper -->
            <div class="page-wrapper">

				<!-- Page Content -->
                <div class="content container-fluid">

					<!-- Content Starts -->
                    @include('admin.layouts.errors')

                    @yield('content')
					<!-- /Content End -->

                </div>
				<!-- /Page Content -->

            </div>
			<!-- /Page Wrapper -->

        </div>
		<!-- /Main Wrapper -->

		<!-- Sidebar Overlay -->
		<div class="sidebar-overlay" data-reff=""></div>

		<!-- jQuery -->
        <script src="{{ asset('assets/admin/js/jquery-3.2.1.min.js') }}"></script>

		<!-- Bootstrap Core JS -->
        <script src="{{ asset('assets/admin/js/popper.min.js') }}"></script>
        <script src="{{ asset('assets/admin/plugins/bootstrap-rtl/js/bootstrap.min.js') }}"></script>

		<!-- Slimscroll JS -->
		<script src="{{ asset('assets/admin/js/jquery.slimscroll.min.js') }}"></script>

		<!-- Custom JS -->
		<script src="{{ asset('assets/admin/js/app.js') }}"></script>

    </body>
</html>

resources/views/admin/layouts/menu.blade.php
<!-- Sidebar -->
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li>
                    <a href="{{ url('/admin') }}"><i class="la la-dashboard"></i> <span style="font-size: 140%">الرئيسية</span></a>
                </li>
                <li class="submenu">
                    <a href="#" ><i class="la la-user"></i> <span style="font-size: 120%"> الموظفيين </span> <span class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li><a href="{{ route('employees.index') }}" style="font-size: 110%">جميع الموظفيين </a></li>
                        <li><a href="{{ route('departments.index') }}" style="font-size: 110%">الأقسام</a></li>
                        <li><a href="{{ route('designations.index') }}" style="font-size: 110%">الوظائف</a></li>
                        <li><a href="{{ route('holidays.index') }}" style="font-size: 110%">الأجازات الرسمية</a></li>
                    </ul>
                    <li>
                        <a href="{{ route('clients.index') }}" ><i class="la la-users"></i> <span style="font-size: 120%"> العملاء </span></a>
                    </li>
                    <li>
                            <a href="{{ route('company_profiles.index') }}" ><i class="la la-building"></i> <span style="font-size: 120%"> بيانات الشركة </span></a>
                        </li>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- /Sidebar -->